"""empty message

Revision ID: b97ba97aab3b
Revises: 9ca6e8e34859
Create Date: 2025-08-13 13:53:14.768664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97ba97aab3b'
down_revision: Union[str, Sequence[str], None] = '9ca6e8e34859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer_create_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_create_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
